"""initial schema

Revision ID: ab709c71570e
Revises: 
Create Date: 2026-06-24 16:59:08.496688
"""
from typing import Sequence, Union

from alembic import context, op
import sqlalchemy as sa



revision: str = 'ab709c71570e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


APPLICATION_TABLES = {
    "areas",
    "countries",
    "dive_logs",
    "dive_points",
    "dive_profile_samples",
    "dive_trips",
    "friend_group_members",
    "friend_groups",
    "friends",
    "marine_weather",
    "regions",
    "shared_album_photos",
    "shared_albums",
    "trip_participants",
    "trip_photos",
    "user_settings",
    "users",
}


def upgrade() -> None:
    """Apply schema changes."""
    if not context.is_offline_mode():
        existing_tables = set(sa.inspect(op.get_bind()).get_table_names())
        existing_application_tables = existing_tables & APPLICATION_TABLES
        if existing_application_tables:
            missing_tables = APPLICATION_TABLES - existing_tables
            if missing_tables:
                missing = ", ".join(sorted(missing_tables))
                raise RuntimeError(
                    "기존 데이터베이스가 초기 스키마와 일치하지 않습니다. "
                    f"누락 테이블: {missing}"
                )
            return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dive_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dive_trips_id'), 'dive_trips', ['id'], unique=False)
    op.create_index(op.f('ix_dive_trips_name'), 'dive_trips', ['name'], unique=False)
    op.create_table('friend_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friend_groups_id'), 'friend_groups', ['id'], unique=False)
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friends_id'), 'friends', ['id'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_index(op.f('ix_regions_name'), 'regions', ['name'], unique=True)
    op.create_table('shared_albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('context_type', sa.String(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_albums_context_id'), 'shared_albums', ['context_id'], unique=False)
    op.create_index(op.f('ix_shared_albums_context_type'), 'shared_albums', ['context_type'], unique=False)
    op.create_index(op.f('ix_shared_albums_id'), 'shared_albums', ['id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ghost_log_threshold_minutes', sa.Integer(), nullable=False),
    sa.Column('bcd', sa.String(), nullable=True),
    sa.Column('regulator', sa.String(), nullable=True),
    sa.Column('dive_computer', sa.String(), nullable=True),
    sa.Column('suit', sa.String(), nullable=True),
    sa.Column('fins', sa.String(), nullable=True),
    sa.Column('mask', sa.String(), nullable=True),
    sa.Column('tank_type', sa.String(), nullable=True),
    sa.Column('default_weight', sa.String(), nullable=True),
    sa.Column('default_log_per_page', sa.Integer(), nullable=False),
    sa.Column('default_log_filter', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_index(op.f('ix_areas_name'), 'areas', ['name'], unique=False)
    op.create_table('friend_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['friend_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friend_group_members_group_id'), 'friend_group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_friend_group_members_id'), 'friend_group_members', ['id'], unique=False)
    op.create_index(op.f('ix_friend_group_members_user_id'), 'friend_group_members', ['user_id'], unique=False)
    op.create_table('marine_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_date', sa.Date(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('water_temp', sa.Float(), nullable=True),
    sa.Column('wave_height', sa.Float(), nullable=True),
    sa.Column('wave_period', sa.Float(), nullable=True),
    sa.Column('wave_direction', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.String(), nullable=True),
    sa.Column('tide_level', sa.String(), nullable=True),
    sa.Column('tide_time', sa.String(), nullable=True),
    sa.Column('current_strength', sa.String(), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marine_weather_id'), 'marine_weather', ['id'], unique=False)
    op.create_index(op.f('ix_marine_weather_region_id'), 'marine_weather', ['region_id'], unique=False)
    op.create_index(op.f('ix_marine_weather_weather_date'), 'marine_weather', ['weather_date'], unique=False)
    op.create_table('shared_album_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('is_representative', sa.Boolean(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['shared_albums.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_album_photos_album_id'), 'shared_album_photos', ['album_id'], unique=False)
    op.create_index(op.f('ix_shared_album_photos_id'), 'shared_album_photos', ['id'], unique=False)
    op.create_table('trip_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['dive_trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_participants_id'), 'trip_participants', ['id'], unique=False)
    op.create_table('trip_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['dive_trips.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_photos_id'), 'trip_photos', ['id'], unique=False)
    op.create_table('dive_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('point_type', sa.String(), nullable=False),
    sa.Column('memo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dive_points_id'), 'dive_points', ['id'], unique=False)
    op.create_index(op.f('ix_dive_points_name'), 'dive_points', ['name'], unique=False)
    op.create_table('dive_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dive_number', sa.Integer(), nullable=True),
    sa.Column('dive_date', sa.Date(), nullable=False),
    sa.Column('dive_point_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('buddy_user_id', sa.Integer(), nullable=True),
    sa.Column('max_depth', sa.Float(), nullable=True),
    sa.Column('avg_depth', sa.Float(), nullable=True),
    sa.Column('entry_time', sa.Time(), nullable=True),
    sa.Column('exit_time', sa.Time(), nullable=True),
    sa.Column('dive_time', sa.Integer(), nullable=True),
    sa.Column('water_temp', sa.Float(), nullable=True),
    sa.Column('visibility', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('site_name', sa.String(), nullable=True),
    sa.Column('buddy', sa.String(), nullable=True),
    sa.Column('start_pressure', sa.Integer(), nullable=True),
    sa.Column('end_pressure', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('profile_samples', sa.Text(), nullable=True),
    sa.Column('import_source', sa.String(), nullable=True),
    sa.Column('import_external_id', sa.String(), nullable=True),
    sa.Column('import_source_file_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['buddy_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dive_point_id'], ['dive_points.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dive_logs_dive_number'), 'dive_logs', ['dive_number'], unique=False)
    op.create_index(op.f('ix_dive_logs_id'), 'dive_logs', ['id'], unique=False)
    op.create_index(op.f('ix_dive_logs_import_external_id'), 'dive_logs', ['import_external_id'], unique=False)
    op.create_index(op.f('ix_dive_logs_import_source'), 'dive_logs', ['import_source'], unique=False)
    op.create_index(op.f('ix_dive_logs_import_source_file_hash'), 'dive_logs', ['import_source_file_hash'], unique=False)
    op.create_table('dive_profile_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dive_log_id', sa.Integer(), nullable=False),
    sa.Column('elapsed_seconds', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dive_log_id'], ['dive_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dive_profile_samples_dive_log_id'), 'dive_profile_samples', ['dive_log_id'], unique=False)
    op.create_index(op.f('ix_dive_profile_samples_elapsed_seconds'), 'dive_profile_samples', ['elapsed_seconds'], unique=False)
    op.create_index(op.f('ix_dive_profile_samples_id'), 'dive_profile_samples', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dive_profile_samples_id'), table_name='dive_profile_samples')
    op.drop_index(op.f('ix_dive_profile_samples_elapsed_seconds'), table_name='dive_profile_samples')
    op.drop_index(op.f('ix_dive_profile_samples_dive_log_id'), table_name='dive_profile_samples')
    op.drop_table('dive_profile_samples')
    op.drop_index(op.f('ix_dive_logs_import_source_file_hash'), table_name='dive_logs')
    op.drop_index(op.f('ix_dive_logs_import_source'), table_name='dive_logs')
    op.drop_index(op.f('ix_dive_logs_import_external_id'), table_name='dive_logs')
    op.drop_index(op.f('ix_dive_logs_id'), table_name='dive_logs')
    op.drop_index(op.f('ix_dive_logs_dive_number'), table_name='dive_logs')
    op.drop_table('dive_logs')
    op.drop_index(op.f('ix_dive_points_name'), table_name='dive_points')
    op.drop_index(op.f('ix_dive_points_id'), table_name='dive_points')
    op.drop_table('dive_points')
    op.drop_index(op.f('ix_trip_photos_id'), table_name='trip_photos')
    op.drop_table('trip_photos')
    op.drop_index(op.f('ix_trip_participants_id'), table_name='trip_participants')
    op.drop_table('trip_participants')
    op.drop_index(op.f('ix_shared_album_photos_id'), table_name='shared_album_photos')
    op.drop_index(op.f('ix_shared_album_photos_album_id'), table_name='shared_album_photos')
    op.drop_table('shared_album_photos')
    op.drop_index(op.f('ix_marine_weather_weather_date'), table_name='marine_weather')
    op.drop_index(op.f('ix_marine_weather_region_id'), table_name='marine_weather')
    op.drop_index(op.f('ix_marine_weather_id'), table_name='marine_weather')
    op.drop_table('marine_weather')
    op.drop_index(op.f('ix_friend_group_members_user_id'), table_name='friend_group_members')
    op.drop_index(op.f('ix_friend_group_members_id'), table_name='friend_group_members')
    op.drop_index(op.f('ix_friend_group_members_group_id'), table_name='friend_group_members')
    op.drop_table('friend_group_members')
    op.drop_index(op.f('ix_areas_name'), table_name='areas')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_shared_albums_id'), table_name='shared_albums')
    op.drop_index(op.f('ix_shared_albums_context_type'), table_name='shared_albums')
    op.drop_index(op.f('ix_shared_albums_context_id'), table_name='shared_albums')
    op.drop_table('shared_albums')
    op.drop_index(op.f('ix_regions_name'), table_name='regions')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_friends_id'), table_name='friends')
    op.drop_table('friends')
    op.drop_index(op.f('ix_friend_groups_id'), table_name='friend_groups')
    op.drop_table('friend_groups')
    op.drop_index(op.f('ix_dive_trips_name'), table_name='dive_trips')
    op.drop_index(op.f('ix_dive_trips_id'), table_name='dive_trips')
    op.drop_table('dive_trips')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
