"""add operations dashboard metrics

Revision ID: d80d19508a75
Revises: ab709c71570e
Create Date: 2026-06-24 17:09:46.024009
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'd80d19508a75'
down_revision: Union[str, Sequence[str], None] = 'ab709c71570e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parser_name', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('selected_count', sa.Integer(), nullable=False),
    sa.Column('saved_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_runs_created_at'), 'import_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_import_runs_id'), 'import_runs', ['id'], unique=False)
    op.create_index(op.f('ix_import_runs_user_id'), 'import_runs', ['user_id'], unique=False)
    op.add_column(
        'dive_points',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.text('CURRENT_TIMESTAMP'),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dive_points', 'created_at')
    op.drop_index(op.f('ix_import_runs_user_id'), table_name='import_runs')
    op.drop_index(op.f('ix_import_runs_id'), table_name='import_runs')
    op.drop_index(op.f('ix_import_runs_created_at'), table_name='import_runs')
    op.drop_table('import_runs')
    # ### end Alembic commands ###
